# Generated by Django 3.1.2 on 2020-11-03 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Produt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Navn', models.CharField(max_length=100)),
                ('ProdutName', models.CharField(max_length=100)),
                ('nikotinindhold', models.IntegerField()),
                ('Prise', models.FloatField()),
                ('Description', models.TextField()),
                ('img', models.ImageField(default='default', upload_to='SnusBildere')),
                ('valdait', models.BooleanField(default=False)),
            ],
        ),
    ]
