# Generated by Django 3.1.2 on 2020-11-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produt',
            name='ListNummer',
            field=models.IntegerField(default=1),
        ),
    ]
