# Generated by Django 3.1.2 on 2020-10-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontakt',
            old_name='FullName',
            new_name='Name',
        ),
    ]
