# Generated by Django 3.1.2 on 2020-10-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snus', '0002_auto_20201029_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnusProdut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Navn', models.CharField(max_length=100)),
                ('ProdutName', models.CharField(max_length=100)),
                ('nikotinindhold', models.IntegerField(max_length=10)),
                ('Prise', models.FloatField(max_length=100)),
                ('Description', models.TextField()),
                ('valdait', models.IntegerField(default=0)),
            ],
        ),
    ]
