# Generated by Django 3.1.2 on 2020-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snus', '0003_auto_20201103_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produt',
            name='Img',
            field=models.ImageField(default='media/SnusBildere/default.png', upload_to='SnusBildere'),
        ),
    ]
