# Generated by Django 3.1.2 on 2020-10-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snus', '0003_snusprodut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snusprodut',
            name='nikotinindhold',
            field=models.IntegerField(),
        ),
    ]
