# Generated by Django 3.1.2 on 2020-10-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snus', '0004_auto_20201030_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='snusprodut',
            name='img',
            field=models.ImageField(default='default', upload_to=''),
        ),
    ]
