# Generated by Django 3.1.2 on 2020-11-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snus', '0005_snusprodut_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snusprodut',
            name='img',
            field=models.ImageField(default='default', upload_to='SnusBildere'),
        ),
    ]
