# Generated by Django 3.1.2 on 2020-11-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snus', '0006_auto_20201102_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snusprodut',
            name='Prise',
            field=models.FloatField(),
        ),
    ]
