# Generated by Django 3.1.2 on 2020-11-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snus', '0007_auto_20201102_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnusProdut',
            new_name='Produt',
        ),
    ]
